version: '3'

services:
  frontend:
    # Specify the build context for the frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile

    # Map the host port to the container port
    ports:
      - "3000:3000"

    # Specify dependencies (if applicable)
    depends_on:
      - backend

    # Specify environment variables if needed
    env_file:
      - environment.env

    # Specify volume for live code reloading (optional)
    volumes:
      - ./frontend:/app

    # Specify the command to run the development server (if different from Dockerfile)
    command: ["npm", "start"]

  backend:
    # Specify the build context for the backend
    build:
      context: ./backend
      dockerfile: Dockerfile

    # Map the host port to the container port
    ports:
      - "5000:5000"

    # Specify environment variables if needed
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py

    # Specify volume for live code reloading (optional)
    volumes:
      - ./backend:/app

    # Specify the command to run the development server (if different from Dockerfile)
    command: ["flask", "run", "--host=0.0.0.0"]

# Define a custom network (if applicable)
networks:
  default:
    driver: bridge
