# Name
name: Dev Ops App CI/CD Pipeline

# Triggers
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows running this workflow from GitHub Actions tab
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/Project/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: npm install
      # run: npm run test
      - run: npm run build

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/Project/backend  # Set working directory to backend
    steps:
      # Checkout code
      - uses: actions/checkout@v4
      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
      # Install dependencies
      - run: pip install -r requirements.txt
      # Run tests
      - run: python -m unittest test_app



  # Define a job for building and pushing Docker images
  docker:
    # Once backend and frontend stages run
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout code
      - uses: actions/checkout@v4
      # Setup Docker
      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: brattdamon
          password: ${{ secrets.GITHUB_TOKEN }}
      # Build frontend Docker image and push to GitHub Container Registry (if on main branch)
      - name: Build and push Docker image (frontend)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./Project/frontend
          tags: ghcr.io/brattdamon/cycalc-frontend:${{ github.sha }},ghcr.io/brattdamon/cycalc-frontend:latest
          push: true
      # Build backend Docker image and push to GitHub Container Registry (if on main branch)
      - name: Build and push Docker image (backend)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./Project/backend
          tags: ghcr.io/brattdamon/cycalc-backend:${{ github.sha }},ghcr.io/brattdamon/cycalc-backend:latest
          push: true
